### ISSUE TITLE
Main page header should be updated

### ISSUE THREAD

**Issue by jwillemsen** [OpenDDS/scoreboard#4]
On `https://scoreboard.opendds.org/` it says `Welcome to DOCGroup Distributed Scoreboard`, that should be `Welcome to the OpenDDS Scoreboard`

**Comment by mitza-oci** [comment]
@jwillemsen is this hard coded in autobuild's `scoreboard.pl`?

**Comment by iguessthislldo** [comment]
This is being fixed in https://github.com/DOCGroup/autobuild/pull/74 and https://github.com/OpenDDS/scoreboard/pull/15
